<?php
echo "<table width='100%' border='0' cellspacing='5' cellpadding='5'><tr>
           <td>
           <form name='cate1' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='single'>
           <INPUT TYPE=submit VALUE='單方'>
           </form>
           </td>
           <td>
           <form name='cate2' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='chemical'>
           <INPUT TYPE=submit VALUE='12組織鹽'>
           </form>
           </td>
           <td>
           <form name='cate3' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='assemble'>
           <INPUT TYPE=submit VALUE='糖球組'>
           </form>
           </td>
           <td>
           <form name='cate4' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='oint'>
           <INPUT TYPE=submit VALUE='油膏'>
           </form>
           </td>
           <td>
           <form name='cate5' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='b'>
           <INPUT TYPE=submit VALUE='12組織鹽複方'>
           </form>
           </td>
           <td>
		   <form name='cate6' method='POST' action='$filename'>
           <INPUT TYPE='hidden' name='action' VALUE='sort'>
           <INPUT TYPE=hidden name='cate' VALUE='m'>
		   <INPUT TYPE=submit VALUE='常用複方'>
           </form>
           </td></tr></table>";
?>
